/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Session */
        post: operations["create_session_api_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Session */
        get: operations["stream_session_api_sessions__session_id__stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/demo/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Demo Session Stream
         * @deprecated
         */
        get: operations["demo_session_stream_api_sessions_demo_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/types/_bundle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Types Bundle
         * @description Frontend type generation only — not callable
         */
        get: operations["types_bundle_api_types__bundle_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AgentFailedEvent */
        AgentFailedEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "agent_failed";
            /** Agent */
            agent: string;
            /** Fallback Taken */
            fallback_taken: string;
            /**
             * User Visible
             * @default true
             */
            user_visible: boolean;
        };
        /** AskUserEvent */
        AskUserEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "ask_user";
            question: components["schemas"]["Question"];
        };
        /** Assumption */
        Assumption: {
            /** Field Id */
            field_id: string;
            /** Assumed Value */
            assumed_value: unknown;
            /** Rationale */
            rationale: string;
            /**
             * Editable
             * @default true
             */
            editable: boolean;
        };
        /** Attachment */
        Attachment: {
            /** Id */
            id: string;
            /** File Name */
            file_name: string;
            /** Format */
            format: string;
            /** Storage Uri */
            storage_uri: string;
            /** Sha256 */
            sha256?: string | null;
        };
        /** CreateSessionRequest */
        CreateSessionRequest: {
            /** User Input */
            user_input: string;
        };
        /** CreateSessionResponse */
        CreateSessionResponse: {
            /** Session Id */
            session_id: string;
        };
        /** DocType */
        DocType: {
            /** Id */
            id: string;
            /** Ko Name */
            ko_name: string;
            /**
             * Domain
             * @default other
             * @enum {string}
             */
            domain: "dispute" | "permit" | "internal" | "other";
            /** Taxonomy Path */
            taxonomy_path?: string[];
        };
        /** Draft */
        Draft: {
            /** Sections */
            sections?: components["schemas"]["DraftSection"][];
        };
        /** DraftParagraph */
        DraftParagraph: {
            /** Text */
            text: string;
            annotations: components["schemas"]["ParagraphAnnotation"];
        };
        /** DraftSection */
        DraftSection: {
            /** Skeleton Id */
            skeleton_id: string;
            /** Title */
            title: string;
            /** Paragraphs */
            paragraphs?: components["schemas"]["DraftParagraph"][];
        };
        /** DraftSectionEvent */
        DraftSectionEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "draft_section";
            section: components["schemas"]["DraftSection"];
        };
        /** EditingReadyEvent */
        EditingReadyEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "editing_ready";
        };
        /** EmptySlot */
        EmptySlot: {
            /** Section Id */
            section_id: string;
            /** Field Id */
            field_id: string;
            /** Placeholder Text */
            placeholder_text: string;
            /**
             * Why Empty
             * @enum {string}
             */
            why_empty: "no_data" | "user_declined" | "low_confidence";
        };
        /** Evidence */
        Evidence: {
            /** Id */
            id: string;
            /**
             * Type
             * @enum {string}
             */
            type: "statute" | "precedent" | "statistic" | "similar_doc" | "convention";
            /** Citation */
            citation: string;
            /** Source Url */
            source_url?: string | null;
            /** Snippet */
            snippet: string;
            /** Relevance Score */
            relevance_score: number;
            /** Applied To */
            applied_to?: string[];
        };
        /** EvidenceNeed */
        EvidenceNeed: {
            /** Id */
            id: string;
            /**
             * Type
             * @enum {string}
             */
            type: "statute" | "precedent" | "statistic" | "similar_doc" | "convention";
            /** Query */
            query: string;
            /**
             * Must Have
             * @default false
             */
            must_have: boolean;
        };
        /** EvidencesFoundEvent */
        EvidencesFoundEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "evidences_found";
            /** Evidences */
            evidences: components["schemas"]["Evidence"][];
        };
        /** Fact */
        Fact: {
            /** Field Id */
            field_id: string;
            /** Value */
            value: unknown;
            /**
             * Source
             * @enum {string}
             */
            source: "explicit" | "inferred" | "defaulted" | "rag";
            /** Confidence */
            confidence: number;
            evidence_span?: components["schemas"]["TextSpan"] | null;
            /** Rationale */
            rationale?: string | null;
        };
        /** FactsExtractedEvent */
        FactsExtractedEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "facts_extracted";
            /** Fact Count */
            fact_count: number;
            /** Unresolved Count */
            unresolved_count: number;
        };
        /** FieldSpec */
        FieldSpec: {
            /** Field Id */
            field_id: string;
            /** Label */
            label: string;
            /**
             * Type
             * @enum {string}
             */
            type: "text" | "number" | "date" | "money" | "duration" | "enum";
            /** Hint */
            hint?: string | null;
            /** Example */
            example?: string | null;
            /**
             * Fill Strategy
             * @enum {string}
             */
            fill_strategy: "ask_user" | "infer" | "rag" | "default";
        };
        /** FillsAppliedEvent */
        FillsAppliedEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "fills_applied";
            /** Fills Count */
            fills_count: number;
            /** Assumptions */
            assumptions?: components["schemas"]["Assumption"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LogicNode */
        LogicNode: {
            /** Id */
            id: string;
            /** Section Id */
            section_id: string;
            /** Claim */
            claim: string;
            /** Sub Claims */
            sub_claims?: components["schemas"]["LogicNode"][];
            /** Depends On Facts */
            depends_on_facts?: string[];
            /** Evidence Needs */
            evidence_needs?: components["schemas"]["EvidenceNeed"][];
            /**
             * Conflict
             * @default false
             */
            conflict: boolean;
        };
        /** Message */
        Message: {
            /** Id */
            id: string;
            /** Role */
            role: string;
            /** Text */
            text: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ParagraphAnnotation */
        ParagraphAnnotation: {
            /**
             * Status
             * @enum {string}
             */
            status: "confirmed" | "inferred" | "defaulted" | "empty" | "evidence_backed";
            /** Fact Refs */
            fact_refs?: string[];
            /** Assumption Refs */
            assumption_refs?: string[];
            /** Evidence Refs */
            evidence_refs?: string[];
            /**
             * Needs User Input
             * @default false
             */
            needs_user_input: boolean;
        };
        /** Question */
        Question: {
            /** Field Ids */
            field_ids: string[];
            /** Prompt */
            prompt: string;
            /** Why */
            why: string;
            /** Examples */
            examples?: string[];
        };
        /**
         * ReviewIssueRef
         * @description ReviewIssue를 stream에 옮기는 경량 ref. 본체는 agents/self_reviewer 모듈에 위치.
         */
        ReviewIssueRef: {
            /**
             * Severity
             * @enum {string}
             */
            severity: "blocker" | "warning" | "info";
            /** Type */
            type: string;
            /** Section Id */
            section_id: string;
            /** Description */
            description: string;
        };
        /** ReviewResultEvent */
        ReviewResultEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "review_result";
            /** Passed */
            passed: boolean;
            /** Issues */
            issues?: components["schemas"]["ReviewIssueRef"][];
        };
        /** SafetyTripEvent */
        SafetyTripEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "safety_trip";
            /** Safety */
            safety: string;
            /** Message */
            message: string;
        };
        /**
         * SchemaBundle
         * @description 프론트엔드 타입 생성을 위한 더미 컨테이너.
         */
        SchemaBundle: {
            /** Stream Event */
            stream_event: components["schemas"]["SkeletonReadyEvent"] | components["schemas"]["FactsExtractedEvent"] | components["schemas"]["FillsAppliedEvent"] | components["schemas"]["AskUserEvent"] | components["schemas"]["EvidencesFoundEvent"] | components["schemas"]["DraftSectionEvent"] | components["schemas"]["ReviewResultEvent"] | components["schemas"]["EditingReadyEvent"] | components["schemas"]["SafetyTripEvent"] | components["schemas"]["AgentFailedEvent"];
            session_state: components["schemas"]["SessionState"];
        };
        /** SessionState */
        SessionState: {
            /** Session Id */
            session_id: string;
            doc_type?: components["schemas"]["DocType"] | null;
            /** Skeleton */
            skeleton?: components["schemas"]["SkeletonNode"][];
            /** Facts */
            facts?: components["schemas"]["Fact"][];
            /** Fills */
            fills?: components["schemas"]["Fact"][];
            /** Assumptions */
            assumptions?: components["schemas"]["Assumption"][];
            /** Logic Tree */
            logic_tree?: components["schemas"]["LogicNode"][];
            /** Evidences */
            evidences?: components["schemas"]["Evidence"][];
            draft?: components["schemas"]["Draft"] | null;
            /** Empty Slots */
            empty_slots?: components["schemas"]["EmptySlot"][];
            /** Pending Questions */
            pending_questions?: components["schemas"]["Question"][];
            /** User Input History */
            user_input_history?: components["schemas"]["Message"][];
            /** User Attachments */
            user_attachments?: components["schemas"]["Attachment"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** SkeletonNode */
        SkeletonNode: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Role */
            role: string;
            /** Logic Anchor */
            logic_anchor: string;
            /** Required Fields */
            required_fields?: components["schemas"]["FieldSpec"][];
            /** Optional Fields */
            optional_fields?: components["schemas"]["FieldSpec"][];
            /** Children */
            children?: components["schemas"]["SkeletonNode"][];
            /** Source */
            source: components["schemas"]["SourceOfficialForm"] | components["schemas"]["SourceUserLibrary"] | components["schemas"]["SourceRag"] | components["schemas"]["SourceLlmInference"] | components["schemas"]["SourceUserAttached"];
        };
        /** SkeletonReadyEvent */
        SkeletonReadyEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "skeleton_ready";
            doc_type: components["schemas"]["DocType"];
            /** Skeleton */
            skeleton: components["schemas"]["SkeletonNode"][];
        };
        /** SourceLlmInference */
        SourceLlmInference: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "llm_inference";
            /** Confidence */
            confidence: number;
        };
        /** SourceOfficialForm */
        SourceOfficialForm: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "official_form";
            /** Form Id */
            form_id: string;
            /** Agency */
            agency: string;
        };
        /** SourceRag */
        SourceRag: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "rag";
            /** Sample Ids */
            sample_ids?: string[];
        };
        /** SourceUserAttached */
        SourceUserAttached: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "user_attached";
            /** File Id */
            file_id: string;
        };
        /** SourceUserLibrary */
        SourceUserLibrary: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "user_library";
            /** Entry Id */
            entry_id: string;
            /** Usage Count */
            usage_count: number;
        };
        /**
         * TextSpan
         * @description 사용자 입력 텍스트의 위치 — UI 하이라이트용.
         */
        TextSpan: {
            /** Start */
            start: number;
            /** End */
            end: number;
            /** Source Message Id */
            source_message_id?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    create_session_api_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateSessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_session_api_sessions__session_id__stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    demo_session_stream_api_sessions_demo_stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    types_bundle_api_types__bundle_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchemaBundle"];
                };
            };
        };
    };
}
